language: ruby
cache:
  apt: true
  bundler: true
  directories:
  - vendor/something
  - .autoconf
rvm:
  - 2.1.2
env:
  - DB=sqlite
bundler_args: --without production
before_script:
  - # export DISPLAY=:99.0
  - # sh -e /etc/init.d/xvfb start
  - # bundle exec RAILS_ENV=test rake db:create db:migrate db:fixtures:load
  - # bundle exec rackup -p 3000 -E test &
  - # sleep 10
script:
  - # bundle exec rake test
  - bundle exec RAILS_ENV=test rake spec
  - # bundle exec rake diff_images
